spring:
  datasource:
    url: jdbc:mysql://localhost:3306/commande-ms
    username: root
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  cloud:
    config:
      enabled: false
    discovery:
      enabled: true
eureka:
  instance:
    preferIpAddress: true

server:
  port: 8092

logging:
  level:
    org.springframework: INFO
    com.example: DEBUG
